In [1]:












import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [2]:
df=pd.read_csv("Iris.csv")
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [8]:
df.drop('Id',axis=1,inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [10]:
df["Species"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [11]:
df["Species"].replace({'Iris-setosa':0, 'Iris-versicolor':1, 'Iris-virginica':2},inplace = True)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


### Train Test split

In [13]:
df = df.select_dtypes(exclude=object) 
x = df.drop('Species',axis=1)
y = df['Species']
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=34)

In [14]:
x

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [15]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64

In [16]:
x_train

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
120            6.9           3.2            5.7           2.3
25             5.0           3.0            1.6           0.2
47             4.6           3.2            1.4           0.2
51             6.4           3.2            4.5           1.5
24             4.8           3.4            1.9           0.2
..             ...           ...            ...           ...
35             5.0           3.2            1.2           0.2
68             6.2           2.2            4.5           1.5
85             6.0           3.4            4.5           1.6
105            7.6           3.0            6.6           2.1
122            7.7           2.8            6.7           2.0

[120 rows x 4 columns]

### Model Training

In [17]:
model=LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

### Testing Data Evaluation

In [18]:
y_pred=model.predict(x_test)
mse=mean_squared_error(y_test,y_pred)
print(f"MSE={mse}")
mae=mean_absolute_error(y_test,y_pred)
print(f"MAE={mae}")
r2score=r2_score(y_test,y_pred)
print(f"R2-Score={r2score}")

MSE=0.05221666209456298
MAE=0.18808724465812535
R2-Score=0.8828054965458686


###  Traning Data Evalution

In [19]:
y_pred_train=model.predict(x_train)
mse=mean_squared_error(y_train,y_pred_train)
print(f"MSE={mse}")
mae=mean_absolute_error(y_train,y_pred_train)
print(f"MAE={mae}")
r2score=r2_score(y_train,y_pred_train)
print(f"R2-Score={r2score}")

MSE=0.04551743525054865
MAE=0.16168625369166445
R2-Score=0.9354299017231897


### Testing on Single Row

In [20]:
x.head(1).T

0
SepalLengthCm  5.1
SepalWidthCm   3.5
PetalLengthCm  1.4
PetalWidthCm   0.2

In [21]:
SepalLengthCm=25
SepalWidthCm =40
PetalLengthCm =24
PetalWidthCm=22

In [22]:
x.columns

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'], dtype='object')

In [23]:
test_array=np.zeros(len(x.columns))
test_array

array([0., 0., 0., 0.])

In [24]:
test_array[0]=SepalLengthCm
test_array[1]=SepalWidthCm
test_array[2]=PetalLengthCm
test_array[3]=PetalWidthCm
test_array

array([25., 40., 24., 22.])

In [25]:
model.predict([test_array])

C:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([13.28904261])

### create Model  pickel File

In [28]:
import pickle
with open("liner_Iris_model.pkl","wb")as f:
    pickle.dump(model,f)

###  create Model json File

In [31]:
import json
with open("Iris_project_data.json","w") as f:
    json.dump(Iris_project_data,f)

In [30]:
Iris_project_data={"Species":{'Iris-setosa':0, 'Iris-versicolor':1, 'Iris-virginica':2},'columns' : list(x.columns)}

In [32]:
import json
with open("Iris_project_data.json","w") as f:
    json.dump(Iris_project_data,f)